<div id="wechat_subscriber" style="display: block; padding: 10px 0; margin: 20px auto; width: 100%; text-align: center;">
  <div style="text-align:center;color: #ccc;font-size:14px;">------ 关注公众号：猩猩的乐园 ------</div>
  <img id="wechat_subscriber_qcode" src="{{ url_for(theme.wechat_subscriber.qcode) }}" style="width: 300px; max-width: 100%;">
  <div>{{ theme.wechat_subscriber.description }}</div>
</div>
